name: GitHub AWS OIDC
on:
  push:
    branches: [oidc-test]
 
permissions:
  id-token: write
  contents: read

jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@4 # Or a specific version
        with: 
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}  # Role ARN you created in step 2
          aws-region: ap-south-1
  
      - name: Test AWS Credentials
        run: aws sts get-caller-identity   
